---
    title:"From Local Structure to Cultural Networks"
    author:"Omar Lizardo"
    date:"`r Sys.Date()`"
---

# Setup
```{r setup}
   knitr::opts_chunk$set(include=FALSE, echo = TRUE, warning = FALSE, message = FALSE)
   library(conflicted)
   library(ergm)
   library(fergm)
   library(ggplot2)
   library(here)   
   library(haven)
   library(dplyr)
   library(sjPlot)
   library(texreg)
   library(tidyr)
```

# Data Wrangling
```{r Importing and creating two mode data frame of people by genres}
    taste.dat <- read_dta("C:/Users/Omar Lizardo/Google Drive/MISC DATA SOURCES/SSI-2012/SSI2012.dta")
    taste.dat <- taste.dat %>% 
      dplyr::select("id", ends_with(c("lis","like")), -starts_with("none")) %>% 
      dplyr::select(c(1:41)) %>% 
      na.omit() %>% 
      mutate(Classical = classicallike * classicallis,
             Opera = operalike * operalis,
             Jazz = jazzlike * jazzlis,
             Broadway = bwaystlike * bwaystlis,
             Easy = moodezlike * moodezlis, 
             Bigband = bbandlike * bbandlis,
             Classic_Rock = croldlike * croldlis,
             Country = countrylike * countrylis,
             Bluegrass = blueglike * blueglis,
             Folk = folklike * folklis,
             Gospel = hymgoslike * hymgoslis,
             Salsa = latlpsallike * latspsallis,
             Rap_Hip_Hop = raphiphoplike * raphiphoplis,
             Blues_RandB = blurblike * blurblis,
             Reggae = reggaelike * reggaelis,
             Pop = toppoplike * toppoplis,
             Contemp_Rock = controcklike * controcklis,
             Indie_Alt = indaltlike * indaltlis,
             Dance_Club = danclublike * danclublis,
             Metal = hvymtllike * hvymtllis
             ) %>%  #people are linked to genres that the both like and listen to
      dplyr::select(id, Classical:Metal) %>% 
      rowwise() %>% 
      mutate(deg = sum(c_across(2:21))) %>% 
      ungroup() %>% 
      dplyr::filter(deg > 0 & deg < 20) 
```

```{r import data on perceived genre demographics}
    #importing data
    dat <- read_dta("C:/Users/Omar Lizardo/Google Drive/MISC DATA SOURCES/SSI-2012/SSI2012.dta") %>% 
        select(classicalfemale:hvymtluc, -ends_with("none")) %>% 
        na.omit() 
    vec <- round(colSums(dat)/nrow(dat),  3)
    tab <- matrix(vec, nrow = 15, ncol = 20)
    dems <- c("Women","Men","White","Black","Hisp.","Asian","College","No Coll.","Young","Mid. Aged","Old","Lower Cls.","Working Cls.","Middle Cls.","Upper Cls.")
    genres <- c("Classical","Opera","Jazz","Musicals","Mood/Easy","Big Band","Classic Rock","Country","Bluegrass","Folk","Gospel","Latin","Rap/Hip Hop","Blues/R&B","Regagae","Pop/Top 40","Cont. Rock","Alt. Rock","EDM/Club","Metal")
    rownames(tab) <- dems
    colnames(tab) <- genres
    
```

```{r Wrangling tile plot data}
   test.mat <- matrix(0, nrow = 15, ncol = 20)
   k <- 1
   i <- 1
   while (k <= 300) {
      for (j in 1:15) {
         p <- prop.test(sum(dat[, k]), nrow(dat), mean(tab[j, ]), correct = FALSE, alternative ="greater")
      test.mat[j, i] <- as.numeric(p$p.value < 0.0001)
      k <- k + 1
      }
   i <- i + 1
   }
   rownames(test.mat) <- dems
   colnames(test.mat) <- genres
   test.mat
   test.dat <-  test.mat %>% 
      data.frame() %>% 
      pivot_longer(
      cols = c(1:20),
      names_to ="genre",
      values_to ="sig"
    )
  per.dat <-  tab %>% 
      data.frame() %>% 
      pivot_longer(
      cols = c(1:20),
      names_to ="genre",
      values_to ="per"
    )
  dem.col <- rep("Women", 20)
  for (i in 2:15) {
     dem.col <- c(dem.col, rep(dems[i], 20))
   }
  test.dat$dems <- dem.col
  test.dat <- relocate(test.dat, sig, .after = dems)
  test.dat$per <- round(per.dat$per, 2)*100
  test.dat$dems <- factor(test.dat$dems, levels = dems)
  test.dat$genre <- factor(test.dat$genre, levels = unique(test.dat$genre))

```

```{r Tile plot of genres by perceived demographics}
   p <- ggplot(test.dat, aes(x = dems, y = genre, fill = sig)) 
   p <- p + geom_tile(color ="white", lwd = 1) 
   p <- p + geom_text(aes(label = per), parse = FALSE,
                        color ="white", size = 4.5) 
   p <- p + theme(legend.position ="none")
   p <- p + labs(x ="", y ="")
   p <- p + scale_x_discrete(position ="top")
   p <- p + scale_y_discrete(limits=rev)
   p <- p + scale_fill_gradient(low ="steelblue", high ="firebrick") 
   p <- p + theme(legend.position ="none",
                    axis.text = 
                     element_text(size = 10)) 
    png(file = here("Plots","genre-dems.png"), width=1000, height=500)
    p
    dev.off()
```



```{r}
   # demog data
   source(here("Functions","demog.dat.R"))
   dat.demog <- demog.dat() %>% 
      dplyr::filter(id %in% unlist(taste.dat$id))  %>% 
      dplyr::select(c("id","college","blk","his","wht","asn","mrc", "female","yng","mid", "old", "low", "wrk", "mcl", "upr")) %>%
      mutate(female = as.numeric(female)) %>% 
      mutate(male = if_else(female == 0, 1, 0)) %>% 
      #mutate(age.n = as.numeric(age), 
             #educ.n = as.numeric(educ.f),
             #type = NA) %>% 
      #mutate(across(college, as.character))  
      dplyr::slice(-which(is.na(female))) 
   taste.mat <- as.matrix(dplyr::filter(taste.dat, id %in% dat.demog$id)[2:21])
   rownames(taste.mat) <- dat.demog$id
   dat.demog <- dat.demog[-1]
   # genre data
   genre.dat <- data.frame(matrix(nrow = 20, ncol = 0))
   rownames(genre.dat) <- names(taste.dat[,2:21])
   genre.dat$college <- test.mat["College", ]
   genre.dat$blk <- test.mat["Black", ]
   genre.dat$his <- test.mat["Hisp.", ]
   genre.dat$asn <- test.mat["Asian", ]
   genre.dat$wht <- test.mat["White", ]
   genre.dat$mrc <- NA
   genre.dat$female <- test.mat["Women", ]
   genre.dat$male <- test.mat["Men", ]
   genre.dat$yng <- test.mat["Young", ]
   genre.dat$mid <- test.mat["Mid. Aged", ]
   genre.dat$old <- test.mat["Old", ]
   genre.dat$low <- test.mat["Lower Cls.", ]
   genre.dat$wrk <- test.mat["Working Cls.", ]
   genre.dat$mcl <- test.mat["Middle Cls.", ]
   genre.dat$upr <- test.mat["Upper Cls.", ]
   dat.demog <- rbind(dat.demog, genre.dat)
   attribute_list <- do.call(list, dat.demog)
   # network object
   taste.net <- network(taste.mat, bipartite = TRUE, vertex.attr = attribute_list)
```


```{r}
      #baseline models
      m1 <- ergm(taste.net ~ edges + 
                    b1star(2) + b2sociality(c(7, 16)), 
              estimate ="MPLE")
      #genre main effects
      m2 <- ergm(taste.net ~ edges +
                    b1star(2) + b2sociality(c(7, 16)) +
                    b2factor("female") + b2factor("yng") + 
                    b2factor("mid") + b2factor("old") + 
                    b2factor("college") + b2factor("blk"), 
              estimate ="MPLE")
      # genre + person man effects
      m3 <- ergm(taste.net ~ edges +
                    b1star(2) + b2sociality(c(7, 16)) +
                    b2factor("female") + b2factor("yng") +
                    b2factor("mid") + b2factor("old") + 
                    b2factor("college") + b2factor("blk") +
                    b1factor("female") + b1factor("yng") + 
                    b1factor("old") + b1factor("college") +
                    b1factor("low") + b1factor("wrk") + b1factor("upr") +
                    b1factor("blk") + b1factor("his") + 
                    b1factor("asn") + b1factor("mrc"),
              estimate ="MPLE")    
      # gender stars model
      m4 <- ergm(taste.net ~ edges +
                    b1star(2) + b2sociality(c(7, 16)) +
                    b2factor("female") + b2factor("yng") +
                    b2factor("mid") + b2factor("old") + 
                    b2factor("college") + b2factor("blk") +
                    b1factor("female") + b1factor("yng") + 
                    b1factor("old") + b1factor("college") +
                    b1factor("low") + b1factor("wrk") + b1factor("upr") +
                    b1factor("blk") + b1factor("his") + 
                    b1factor("asn") + b1factor("mrc") +
                    b1twostar("female", "female", levels2 = c(6)) + 
                    b1twostar("male", "male", levels2 = c(6)), 
              estimate ="MPLE") 
      # age stars model
      m5 <- ergm(taste.net ~ edges +
                    b1star(2) + b2sociality(c(7, 16)) +
                    b2factor("female") + b2factor("yng") +
                    b2factor("mid") + b2factor("old") + 
                    b2factor("college") + b2factor("blk") +
                    b1factor("female") + b1factor("yng") + 
                    b1factor("old") + b1factor("college") +
                    b1factor("low") + b1factor("wrk") + b1factor("upr") +
                    b1factor("blk") + b1factor("his") + 
                    b1factor("asn") + b1factor("mrc") +
                    b1twostar("yng", "yng", levels2 = c(6)) + 
                    b1twostar("mid", "mid", levels2 = c(6)) + 
                    b1twostar("old", "old", levels2 = c(6)),
              estimate ="MPLE") 
      # race stars model
      m6 <- ergm(taste.net ~ edges +
                    b1star(2) + b2sociality(c(7, 16)) +
                    b2factor("female") + b2factor("yng") +
                    b2factor("mid") + b2factor("old") + 
                    b2factor("college") + b2factor("blk") +
                    b1factor("female") + b1factor("yng") + 
                    b1factor("old") + b1factor("college") +
                    b1factor("low") + b1factor("wrk") + b1factor("upr") +
                    b1factor("blk") + b1factor("his") + 
                    b1factor("asn") + b1factor("mrc") +
                    b1twostar("blk", "blk", levels2 = c(6)) + 
                    b1twostar("his", "his", levels2 = c(6)) + 
                    b1twostar("asn", "asn", levels2 = c(6)) + 
                    b1twostar("wht", "wht", levels2 = c(6)),
              estimate ="MPLE")
      # educ stars model
      m7 <- ergm(taste.net ~ edges +
                    b1star(2) + b2sociality(c(7, 16)) +
                    b2factor("female") + b2factor("yng") +
                    b2factor("mid") + b2factor("old") + 
                    b2factor("college") + b2factor("blk") +
                    b1factor("female") + b1factor("yng") + 
                    b1factor("old") + b1factor("college") +
                    b1factor("low") + b1factor("wrk") + b1factor("upr") +
                    b1factor("blk") + b1factor("his") + 
                    b1factor("asn") + b1factor("mrc") +
                    b1twostar("college", "college", levels2 = c(6)),
              estimate ="MPLE")
      # class stars model
      m8 <- ergm(taste.net ~ edges +
                    b1star(2) + b2sociality(c(7, 16)) +
                    b2factor("female") + b2factor("yng") +
                    b2factor("mid") + b2factor("old") + 
                    b2factor("college") + b2factor("blk") +
                    b1factor("female") + b1factor("yng") + 
                    b1factor("old") + b1factor("college") +
                    b1factor("low") + b1factor("wrk") + b1factor("upr") +
                    b1factor("blk") + b1factor("his") + 
                    b1factor("asn") + b1factor("mrc") +
                    b1twostar("college", "college", levels2 = c(6)) +
                    b1twostar("low", "low", levels2 = c(6)) +
                    b1twostar("wrk", "wrk", levels2 = c(6)) +
                    b1twostar("mcl", "mcl", levels2 = c(6)) +
                    b1twostar("upr", "upr", levels2 = c(6)),
              estimate ="MPLE")
      m9 <- ergm(taste.net ~ edges +
                    b1star(2) + b2sociality(c(7, 16)) +
                    b2factor("female") + b2factor("yng") +
                    b2factor("mid") + b2factor("old") + 
                    b2factor("college") + b2factor("blk") +
                    b1factor("female") + b1factor("yng") + 
                    b1factor("old") + b1factor("college") +
                    b1factor("low") + b1factor("wrk") + b1factor("upr") +
                    b1factor("blk") + b1factor("his") + 
                    b1factor("asn") + b1factor("mrc") +
                    b1twostar("college", "college", levels2 = c(6)) +
                    b1twostar("low", "low", levels2 = c(6)) +
                    b1twostar("wrk", "wrk", levels2 = c(6)) +
                    b1twostar("mcl", "mcl", levels2 = c(6)) +
                    b1twostar("upr", "upr", levels2 = c(6)) +
                    b1twostar("college", "low", levels2 = c(6)) +
                    b1twostar("college", "wrk", levels2 = c(6)) +
                    b1twostar("college", "mcl", levels2 = c(6)) +
                    b1twostar("college", "upr", levels2 = c(6)),
              estimate ="MPLE")
```

```{r}
      texreg(list(m1, m2, m3), 
             file = here("Tabs","ergm-tab1.tex"),
             custom.coef.names =  c("Edges","Person 2-Star", 
                                   "Classic Rock","Pop",
                                   "Genre: Women","Genre: Young",
                                   "Genre: Mid", "Genre: Old",
                                   "Genre: College", "Genre: Black", 
                                   "Person: Woman", "Person: Young",
                                   "Person: Old",  "Person: College",
                                   "Person: Lower Cls.",  "Person: Working Cls.",
                                   "Person: Upper Cls.",
                                   "Person: Black", "Person: Hisp.",
                                   "Person: Asian", "Person: Mult."),
             booktabs = TRUE, use.packages = FALSE, digits = 4,
             caption = "Coefficient estimates of two-mode ERGMs models obtained via pseudo-likelihood.",
             label = "tab:reg1"
             )

      texreg(list(m4, m5, m6),
             file = here("Tabs","ergm-tab2.tex"),
             custom.coef.names =  c("Edges","Person 2-Star", 
                                   "Classic Rock","Pop",
                                   "Genre: Women","Genre: Young",
                                   "Genre: Mid", "Genre: Old",
                                   "Genre: College", "Genre: Black", 
                                   "Person: Woman", "Person: Young",
                                   "Person: Old",  "Person: College",
                                   "Person: Lower Cls.",  "Person: Working Cls.",
                                   "Person: Upper Cls.",
                                   "Person: Black", "Person: Hisp.",
                                   "Person: Asian", "Person: Mult.",
                                   "G(Women)-P(Woman)-G(Women)",
                                   "G(Men)-P(Man)-G(Men)",
                                   "G(Young)-P(Young)-G(Young)",
                                   "G(Mid.)-P(Mid.)-G(Mid.)",
                                   "G(Old)-P(Old)-G(Old)",
                                   "G(Black)-P(Black)-G(Black)",
                                   "G(Hisp.)-P(Hisp.)-G(Hisp.)",
                                   "G(Asian)-P(Asian)-G(Asian)",
                                   "G(White)-P(White)-G(White)"),
             booktabs = TRUE, longtable = TRUE, 
             use.packages = FALSE, digits = 4,
             caption = "Coefficient estimates of two-mode ERGMs models obtained via pseudo-likelihood.",
             label = "tab:reg2",
             omit.coef = "(edges)|(b1star2)|(b2sociality)|(b2factor)"
             )
      texreg(list(m7, m8, m9),
             file = here("Tabs","ergm-tab3.tex"),
             custom.coef.names =  c("Edges","Person 2-Star", 
                                   "Classic Rock","Pop",
                                   "Genre: Women","Genre: Young",
                                   "Genre: Mid", "Genre: Old",
                                   "Genre: College", "Genre: Black", 
                                   "Person: Woman", "Person: Young",
                                   "Person: Old",  "Person: College",
                                   "Person: Lower Cls.",  "Person: Working Cls.",
                                   "Person: Upper Cls.",
                                   "Person: Black", "Person: Hisp.",
                                   "Person: Asian", "Person: Mult.",
                                   "G(College)-P(College)-G(College)",
                                   "G(Lower)-P(Lower)-G(Lower)",
                                   "G(Working)-P(Working)-G(Working)",
                                   "G(Middle)-P(Middle)-G(Middle)",
                                   "G(Upper)-P(Upper)-G(Upper)",
                                   "G(Lower)-P(College)-G(Lower)",
                                   "G(Working)-P(College)-G(Working)",
                                   "G(Middle)-P(College)-G(Middle)",
                                   "G(Upper)-P(College)-G(Upper)"),
             booktabs = TRUE, longtable = TRUE, 
             use.packages = FALSE, digits = 4,
             caption = "Coefficient estimates of two-mode ERGMs models obtained via pseudo-likelihood.",
             label = "tab:reg3",
             omit.coef = "(edges)|(b1star2)|(b2sociality)|(b2factor)"
             )
```
